services:
  vbot:
    container_name: vbot
    build: .
    env_file:
      - private.env
      - public.env
    volumes:
      - ./src:/app/src:Z
      - ./Cargo.toml:/app/Cargo.toml:Z
      - ./Cargo.lock:/app/Cargo.lock:Z
      - ./data:/app/data:Z
      - ./public.env:/app/public.env:Z
      - cargo-target:/app/target
    restart: unless-stopped

volumes:
  cargo-target:
